const params=new URLSearchParams(location.search),kind=params.get('component'),state=params.get('state')||'live',main=document.getElementById('preview');document.body.dataset.gallery=params.get('gallery')==='1';const H=TurboUI;
function add(id,label,node){const box=document.createElement('section');box.className='example';box.id=id;const caption=document.createElement('p');caption.className='label';caption.textContent=label;box.append(caption,node);main.append(box)}
const backdrop=(...children)=>{const root=H.chromeBackdrop();root.append(...children);return root};
if(kind==='button'){[['primary',{}],['compact',{size:'compact',quiet:true}],['compact-end',{size:'compact',quiet:true,icon:'caret-down',iconPosition:'end'}],['trailing',{icon:'caret-down',iconPosition:'end'}],['quiet',{quiet:true}],['icon',{quiet:true,iconOnly:true,icon:'settings'}],['disabled',{disabled:true}]].forEach(([id,options])=>add(id,id,H.button({label:id==='icon'?'Settings':id==='compact-end'?'Add':'Show all transactions',...options,onClick:()=>{document.getElementById('result').textContent='Action activated'}})));const result=document.createElement('p');result.id='result';result.setAttribute('role','status');main.append(result)}
if(kind==='avatar'){add('profile','Member profile',H.avatar({name:'Arun Sharma',size:'profile'}));add('hub','Hub graphic',H.avatar({size:'hub',graphic:true}));add('merchant','Merchant',H.avatar({name:'Amazon',size:'merchant'}));add('initials','Initials',H.avatar({name:'Arun Sharma'}));add('large','Large / generic family',H.avatar({large:true,graphic:true}))}
if(kind==='badge'){add('default','Default',H.badge('Manager'));add('role','Role',H.badge('Manager',{variant:'role'}));add('relationship','Relationship',H.badge('Wife',{variant:'relationship'}));add('relationship-long','Long relationship',H.badge('Extended family member',{variant:'relationship'}));}
if(kind==='limit'){[['member',0,45000],['member-partial',10000,45000],['member-full',45000,45000]].forEach(([id,spent,limit])=>add(id,id,H.limit({spent,limit,label:'Monthly Limit',variant:'member'})));[['circular',14500,100000],['circular-empty',0,45000],['circular-full',45000,45000],['circular-over',50000,45000],['circular-zero',0,0]].forEach(([id,spent,limit])=>add(id,id,H.limit({spent,limit,label:'Monthly Limit',variant:'circular'})));add('default','Partial',H.limit({spent:14500,limit:100000}));add('empty','Unused',H.limit({spent:0,limit:45000}));add('full','At limit',H.limit({spent:45000,limit:45000}))}
if(kind==='tabs'){let selected=state==='members'?'Members':state==='analytics'?'Analytics':'Spends';const host=document.createElement('div');function paint(){host.replaceChildren(H.tabs({id:'sample',items:['Spends','Members','Analytics'],selected,onChange:v=>{selected=v;paint();document.getElementById('sample-panel').textContent=v}}))}paint();add('default','Sections',host);const panel=document.createElement('div');panel.id='sample-panel';panel.setAttribute('role','tabpanel');panel.textContent=selected;main.append(panel)}
if(kind==='row'){add('compact','Compact',H.row({name:'Amazon',detail:'04 Dec 2023, 10:00 PM',amount:1595,variant:'compact'}));add('compact-long','Compact / long title',H.row({name:'An independently owned neighbourhood convenience store',detail:'22 Nov 2023, 10:00 PM',amount:12345,variant:'compact'}));add('compact-minimal','Compact / without detail',H.row({name:'UPI',amount:2350,variant:'compact'}));add('default','Transaction',H.row({name:'Amazon',detail:'04 Dec 2023 · 10:00 PM',amount:1595}));add('long','Long title',H.row({name:'An independently owned neighbourhood convenience store',detail:'22 Nov 2023',amount:12345}));add('minimal','Without detail',H.row({name:'UPI',amount:2350}))}
if(kind==='member'){add('profile-joined','Profile / joined',H.member({name:'Arun Sharma',role:'Manager',spent:0,limit:45000,variant:'profile'}));add('profile-pending','Profile / pending',H.member({name:'Kavya Sharma',role:'Manager',relation:'Wife',pending:true,variant:'profile'}));add('profile-no-tags','Profile / without tags',H.member({name:'Neha Sharma',spent:10000,limit:45000,variant:'profile'}));add('profile-long','Profile / long content',H.member({name:'An independently named extended family member',role:'Manager',relation:'Extended family member',pending:true,statusText:'This member has not accepted the invitation to join the family hub yet.',variant:'profile'}));add('joined','Joined',H.member({name:'Arun Sharma',role:'Manager',spent:10000,limit:45000}));add('pending','Pending',H.member({name:'Kavya Sharma',role:'Manager',relation:'Wife',pending:true}))}
if(kind==='chart')add('default','Spending trend',H.chart({}));
if(kind==='summary'){add('default','Family Hub',H.summary({}));add('default-action','Horizontal / options',H.summary({action:{label:'Hub options',icon:'more',onClick:()=>{}}}));add('centered','Centered',H.summary({variant:'centered'}));add('centered-action','Centered / options',H.summary({variant:'centered',action:{label:'Hub options',icon:'more',onClick:()=>{}}}));add('centered-long','Centered / long name',H.summary({name:'The extended Sharma family household',variant:'centered'}))}
if(kind==='statusbar')add('default','Phone status',H.statusbar());

if(kind==='button'&&state!=='live'){const target=main.querySelector('#'+(params.get('target')||'primary')+' .th-button');if(target){if(state==='disabled')target.disabled=true;else if(state==='focus-visible')target.focus();else target.dataset.previewState=state;}}


if(kind==='chrome-backdrop'){const root=H.chromeBackdrop();root.classList.add('backdrop-example-frame');main.append(root);}

if(kind==='navigation'){const action={label:"Back",icon:"back",onClick:()=>document.getElementById("nav-result").textContent="Back activated"};add("title","Title only",backdrop(H.navigation({title:"Hub Details"})));add("back","Back + title",backdrop(H.navigation({title:"Add Member",left:action})));add("both","Back + title + action",backdrop(H.navigation({title:"Hub Details",left:action,right:{label:"Settings",icon:"settings",onClick:()=>document.getElementById("nav-result").textContent="Settings activated"}})));add("long","Long title",backdrop(H.navigation({title:"Payment request awaiting manager approval",left:action})));const result=document.createElement("p");result.id="nav-result";result.setAttribute("role","status");main.append(result)}

if(kind==='page-header'){add('full','Heading, subtext and icon',backdrop(H.pageHeader({heading:'Nykaa',subtext:'nykaaphoenixblr@hdfcbank',verified:true,icon:'payment'})));add('heading','Heading only',backdrop(H.pageHeader({heading:'Accounts & Cards'})));add('long','Long heading and subtext',backdrop(H.pageHeader({heading:'Neighbourhood family essentials store',subtext:'merchant.reference@bank'})))}
