const params=new URLSearchParams(location.search),kind=params.get('component'),state=params.get('state')||'live',main=document.getElementById('preview');document.body.dataset.gallery=params.get('gallery')==='1';const H=TurboUI;
function add(id,label,node){const box=document.createElement('section');box.className='example';box.id=id;const caption=document.createElement('p');caption.className='label';caption.textContent=label;box.append(caption,node);main.append(box)}
const backdrop=(...children)=>{const root=H.chromeBackdrop();root.append(...children);return root};
if(kind==='button'){[['primary',{}],['compact',{size:'compact',quiet:true}],['compact-end',{size:'compact',quiet:true,icon:'caret-down',iconPosition:'end'}],['trailing',{icon:'caret-down',iconPosition:'end'}],['quiet',{quiet:true}],['icon',{quiet:true,iconOnly:true,icon:'settings'}],['disabled',{disabled:true}]].forEach(([id,options])=>add(id,id,H.button({label:id==='icon'?'Settings':id==='compact-end'?'Add':'Show all transactions',...options,onClick:()=>{document.getElementById('result').textContent='Action activated'}})));const result=document.createElement('p');result.id='result';result.setAttribute('role','status');main.append(result)}
if(kind==='avatar'){add('profile','Member profile',H.avatar({name:'Arun Sharma',size:'profile'}));add('hub','Hub graphic',H.avatar({size:'hub',graphic:true}));add('merchant','Merchant',H.avatar({name:'Amazon',size:'merchant'}));add('initials','Initials',H.avatar({name:'Sample Member'}));add('large','Large / generic family',H.avatar({large:true,graphic:true}))}
if(kind==='badge'){add('default','Default',H.badge('Manager'));add('role','Role',H.badge('Manager',{variant:'role'}));add('relationship','Relationship',H.badge('Wife',{variant:'relationship'}));add('relationship-long','Long relationship',H.badge('Extended family member',{variant:'relationship'}));add('success','Success',H.badge('Active',{variant:'success'}));add('warning','Warning with icon',H.badge('Add details',{variant:'warning',icon:'warning-circle'}));}
if(kind==='limit'){add('setup','setup',H.limit({label:'Monthly Limit',variant:'setup',action:{label:'Set up the Hub’s monthly limit',icon:'limit',onClick:()=>{}}}));add('setup-glass','setup-glass',backdrop(H.limit({label:'Monthly Limit',variant:'setup',tone:'glass',action:{label:'Set up the Hub’s monthly limit',icon:'limit',onClick:()=>{}}})));}
if(kind==='limit')add('circular-glass','circular-glass',backdrop(H.limit({spent:14500,limit:100000,label:'Monthly Limit',variant:'circular',tone:'glass'})));
if(kind==='limit'){[['member',0,45000],['member-partial',10000,45000],['member-full',45000,45000]].forEach(([id,spent,limit])=>add(id,id,H.limit({spent,limit,label:'Monthly Limit',variant:'member'})));[['circular',14500,100000],['circular-empty',0,45000],['circular-full',45000,45000],['circular-over',50000,45000],['circular-zero',0,0]].forEach(([id,spent,limit])=>add(id,id,H.limit({spent,limit,label:'Monthly Limit',variant:'circular'})));add('default','Partial',H.limit({spent:14500,limit:100000}));add('empty','Unused',H.limit({spent:0,limit:45000}));add('full','At limit',H.limit({spent:45000,limit:45000}))}
if(kind==='tabs'){let selected=state==='members'?'Members':state==='analytics'?'Analytics':'Spends';const host=document.createElement('div');function paint(){host.replaceChildren(H.tabs({id:'sample',items:['Spends','Members','Analytics'],selected,onChange:v=>{selected=v;paint();document.getElementById('sample-panel').textContent=v}}))}paint();add('default','Sections',host);add('chrome','On chrome',backdrop(H.tabs({id:'sample-chrome',items:['Spends','Members','Analytics'],selected:'Members',tone:'chrome',onChange:()=>{}})));add('segmented','Segmented (on a light sheet)',H.tabs({id:'sample-seg',items:['My Hubs','Shared with me'],selected:'My Hubs',tone:'segmented',onChange:()=>{}}));const panel=document.createElement('div');panel.id='sample-panel';panel.setAttribute('role','tabpanel');panel.textContent=selected;main.append(panel)}
if(kind==='row'){add('compact','Compact',H.row({name:'Amazon',detail:'04 Dec 2023, 10:00 PM',amount:1595,variant:'compact'}));add('compact-long','Compact / long title',H.row({name:'An independently owned neighbourhood convenience store',detail:'22 Nov 2023, 10:00 PM',amount:12345,variant:'compact'}));add('compact-minimal','Compact / without detail',H.row({name:'UPI',amount:2350,variant:'compact'}));add('default','Transaction',H.row({name:'Amazon',detail:'04 Dec 2023 · 10:00 PM',amount:1595}));add('long','Long title',H.row({name:'An independently owned neighbourhood convenience store',detail:'22 Nov 2023',amount:12345}));add('minimal','Without detail',H.row({name:'UPI',amount:2350}))}
if(kind==='member')add('profile-chevron','Profile / with chevron',H.member({name:'Kavya Sharma',role:'Manager',relation:'Wife',spent:1200,limit:45000,variant:'profile',chevron:true}));
if(kind==='member'){add('profile-joined','Profile / joined',H.member({name:'Arun Sharma',role:'Manager',spent:0,limit:45000,variant:'profile'}));add('profile-pending','Profile / pending',H.member({name:'Kavya Sharma',role:'Manager',relation:'Wife',pending:true,variant:'profile'}));add('profile-no-tags','Profile / without tags',H.member({name:'Neha Sharma',spent:10000,limit:45000,variant:'profile'}));add('profile-long','Profile / long content',H.member({name:'An independently named extended family member',role:'Manager',relation:'Extended family member',pending:true,statusText:'This member has not accepted the invitation to join the family hub yet.',variant:'profile'}));add('joined','Joined',H.member({name:'Arun Sharma',role:'Manager',spent:10000,limit:45000}));add('pending','Pending',H.member({name:'Kavya Sharma',role:'Manager',relation:'Wife',pending:true}))}
if(kind==='chart')add('default','Spending trend',H.chart({}));
if(kind==='summary'){add('default','Family Hub',H.summary({}));add('default-action','Horizontal / options',H.summary({action:{label:'Hub options',icon:'more',onClick:()=>{}}}));add('centered','Centered',H.summary({variant:'centered'}));add('centered-action','Centered / options',H.summary({variant:'centered',action:{label:'Hub options',icon:'more',onClick:()=>{}}}));add('centered-long','Centered / long name',H.summary({name:'The extended Sharma family household',variant:'centered'}));add('centered-chrome','Centered / on chrome',backdrop(H.summary({variant:'centered',tone:'chrome'})))}
if(kind==='statusbar'){add('default','Phone status',backdrop(H.statusbar()));const light=document.createElement('div');light.style.background='#fff';light.append(H.statusbar({tone:'light'}));add('light','Light surface',light);}

if(kind==='button'){
  for(const [id,label,options] of [
    ['camera','Camera / flash',{icon:'flash'}],
    ['camera-gallery','Camera / gallery',{icon:'gallery'}],
    ['camera-disabled','Camera / disabled',{icon:'flash',disabled:true}]
  ]){
    const context=document.createElement('div');context.className='camera-action-context';
    context.append(H.button({label,variant:'camera',...options,onClick:()=>{document.getElementById('result').textContent='Camera action activated'}}));
    add(id,label,context);
  }
}
if(kind==='button'&&state!=='live'){const target=main.querySelector('#'+(params.get('target')||'primary')+' .th-button');if(target){if(state==='disabled')target.disabled=true;else if(state==='focus-visible')target.focus();else target.dataset.previewState=state;}}


if(kind==='chrome-backdrop'){const root=H.chromeBackdrop();root.classList.add('backdrop-example-frame');main.append(root);}

if(kind==='navigation'){const action={label:"Back",icon:"back",onClick:()=>document.getElementById("nav-result").textContent="Back activated"};add("title","Title only",backdrop(H.navigation({title:"Hub Details"})));add("back","Back + title",backdrop(H.navigation({title:"Add Member",left:action})));add("both","Back + title + action",backdrop(H.navigation({title:"Hub Details",left:action,right:{label:"Settings",icon:"settings",onClick:()=>document.getElementById("nav-result").textContent="Settings activated"}})));add("long","Long title",backdrop(H.navigation({title:"Payment request awaiting manager approval",left:action})));const result=document.createElement("p");result.id="nav-result";result.setAttribute("role","status");main.append(result)}

if(kind==='page-header'){add('action','Heading with action',backdrop(H.pageHeader({heading:'Turbo Hubs',action:H.button({label:'New Hub',icon:'plus',size:'compact',variant:'glass',shape:'pill',onClick:()=>{}})})));add('full','Heading, subtext and icon',backdrop(H.pageHeader({heading:'Nykaa',subtext:'nykaaphoenixblr@hdfcbank',verified:true,icon:'payment'})));add('heading','Heading only',backdrop(H.pageHeader({heading:'Accounts & Cards'})));add('long','Long heading and subtext',backdrop(H.pageHeader({heading:'Neighbourhood family essentials store',subtext:'merchant.reference@bank'})))}

if(kind==='avatar')add('image','Merchant / image',H.avatar({name:'Swiggy',size:'merchant',src:'/app/prototypes/hub-dashboard/assets/merchants/swiggy.png'}));
if(kind==='row')add('compact-by','Compact / spent by',H.row({name:'Nykaa',detail:'27 Nov 2023, 01:45 PM',amount:2400,variant:'compact',by:'Neha',avatarSrc:'/app/prototypes/hub-dashboard/assets/merchants/nykaa.png'}));
if(kind==='row')add('compact-image','Compact / merchant image',H.row({name:'Swiggy',detail:'28 Nov 2023, 11:42 AM',amount:1200,variant:'compact',avatarSrc:'/app/prototypes/hub-dashboard/assets/merchants/swiggy.png'}));

if(kind==='avatar')add('stack','Stack (overlapping group)',(()=>{const g=document.createElement('div');g.style.cssText='display:flex;padding-left:8px';for(const m of ['Arun Sharma','Kavya Sharma','Neha Sharma']){const v=H.avatar({name:m,size:'stack'});v.style.marginLeft='-8px';g.append(v);}return g;})());if(kind==='avatar')add('badge-success','Icon / success badge',H.avatar({name:'UPI',graphic:'upi-fill',badge:'success'}));
if(kind==='avatar')add('editable','Editable Hub graphic',H.avatar({size:'hub',graphic:true,editable:true,onEdit:()=>{}}));
if(kind==='avatar-edit'){add('default','Edit action',H.avatarEdit());add('disabled','Disabled',H.avatarEdit({disabled:true}));}
if(kind==='avatar-edit'&&state!=='live'){const target=main.querySelector('#'+(params.get('target')||'default')+' .th-avatar-edit');if(target){if(state==='disabled')target.disabled=true;else if(state==='focus-visible')target.focus();else target.dataset.previewState=state;}}

if(kind==='button')add('list','List action',H.button({label:'Invite Member',icon:'invite',variant:'list',onClick:()=>{}}));
if(kind==='button')add('warning','Warning',H.button({label:'Add details',icon:'warning-circle',variant:'warning',size:'compact',onClick:()=>{}}));
if(kind==='button')add('glass','Glass (on chrome)',backdrop(H.button({label:'View members',variant:'glass',onClick:()=>{}})));if(kind==='button')add('inverse-pill','Inverse pill (create on chrome)',backdrop(H.button({label:'New Hub',icon:'plus',size:'compact',variant:'inverse',shape:'pill',onClick:()=>{}})));if(kind==='button')add('inverse','Inverse (primary on chrome)',backdrop(H.button({label:'Done',variant:'inverse',onClick:()=>{}})));
if(kind==='button'){add('danger','Danger',H.button({label:'Decline',variant:'danger',onClick:()=>{}}));add('danger-compact','Danger / compact',H.button({label:'Remove member',variant:'danger',size:'compact',onClick:()=>{}}));}

if(kind==='navigation'){add('icons-back','Icon only',backdrop(H.navigation({variant:'icons-only',left:{label:'Back',icon:'navigation-back',onClick:()=>{}}})));add('icons-both','Two icons',backdrop(H.navigation({variant:'icons-only',left:{label:'Back',icon:'navigation-back',onClick:()=>{}},right:{label:'Help',icon:'help',onClick:()=>{}}})));}

if(kind==='avatar')add('contact','Editable contact',H.avatar({name:'Kavya Sharma',size:'contact',editable:true,editLabel:'Edit member image',onEdit:()=>{}}));

if(kind==='action-footer'){add('single','Single action',H.actionFooter({actions:[{label:'Next',onClick:()=>{}}]}));add('multiple','Multiple actions',H.actionFooter({actions:[{label:'Continue',onClick:()=>{}},{label:'Cancel',quiet:true,onClick:()=>{}}]}));}

if(kind==='avatar')add('contact-medium','Editable contact · medium',H.avatar({name:'Kavya Sharma',size:'contact-medium',editable:true,editLabel:'Edit member image',onEdit:()=>{}}));

if(kind==='action-footer'){const next=H.button({label:'Next',disabled:true});const acceptance=H.check({id:'footer-acceptance',label:'I accept the example conditions.',onChange:value=>{next.disabled=!value}});const footer=H.actionFooter({content:[acceptance]});footer.append(next);add('acceptance','Acceptance and action',footer);}
