const params=new URLSearchParams(location.search),kind=params.get('component'),H=TurboUI,main=document.getElementById('preview');document.body.dataset.gallery=params.get('gallery')==='1';
function add(id,options){const box=document.createElement('section');box.id=id;box.className='example'+(options.variant==='digit'?' example--digit':'');const caption=document.createElement('p');caption.className='label';caption.textContent=id;let node;const api=kind==='switch'?'toggle':kind;node=H[api]({id:'sample-'+id,label:kind==='field'?'Full name':kind==='select'?'Relationship with you':kind==='switch'?'Manager role':'Member meets the age and document requirements',items:[['','Choose relationship'],['Wife','Wife'],['Son','Son']],...options,onChange:value=>{if(node.setChecked)node.setChecked(value)}});box.append(caption,node);main.append(box)}
if(kind==='field'){add('amount',{label:'Amount',value:'2500',prefix:'₹',prominent:true});add('default',{value:'Kavya Sharma'});add('placeholder',{label:'Hub Name',variant:'placeholder'});add('placeholder-filled',{label:'Hub Name',variant:'placeholder',value:'Family Hub'});add('placeholder-error',{label:'Hub Name',variant:'placeholder',error:'Enter a name for your Hub.'});add('placeholder-disabled',{label:'Hub Name',variant:'placeholder',disabled:true});add('optional',{label:'Nickname',optional:true,placeholder:'Enter nickname'});add('error',{error:'Enter the member’s full name.'});add('disabled',{value:'Kavya Sharma',disabled:true})}
if(kind==='select'){add('default',{value:'Wife'});add('error',{error:'Choose a relationship.'});add('disabled',{value:'Wife',disabled:true})}
if(kind==='switch'){add('off',{description:'Managers can manage members and authorise payments.'});add('on',{checked:true});add('disabled',{checked:true,disabled:true})}
if(kind==='check'){add('confirmation',{});add('link',{label:'I agree to the',link:{label:'Terms and conditions',href:'#',onClick:()=>{}}});add('card',{card:true,label:'Physical Card',description:'Delivered to the member’s address.',price:'₹500 / annum'});add('selected',{card:true,label:'Physical Card',description:'Delivered to the member’s address.',price:'₹500 / annum',checked:true});add('violet',{card:true,tone:'violet',label:'UPI',description:'Linked to your account.',price:'Free',checked:true});add('error',{error:'Confirm the member’s age and documents.'});add('disabled',{disabled:true})}

if(kind==='slider'){const inr=v=>'₹'+v.toLocaleString('en-IN');add('default',{label:'Monthly limit',min:500,max:100000,step:500,value:5000,format:inr});add('maximum',{label:'Monthly limit',min:500,max:100000,step:500,value:100000,format:inr});add('disabled',{label:'Monthly limit',min:500,max:100000,step:500,value:45000,format:inr,disabled:true});}
if(kind==='switch')add('info',{info:true,label:'Manager role',onInfo:()=>{}});
if(kind==='info-pill'){const section=document.createElement('section');section.id='default';section.append(H.infoPill());main.append(section);}

if(kind==='field'){add('digit',{variant:'digit',label:'Digit 1 of 6'});add('digit-filled',{variant:'digit',label:'Digit 1 of 6',value:'4'});add('digit-disabled',{variant:'digit',label:'Digit 1 of 6',value:'4',disabled:true});}
if(kind==='otp'){add('empty',{label:'6-digit code'});add('partial',{label:'6-digit code',value:'482'});add('complete',{label:'6-digit code',value:'482913'});add('error',{label:'6-digit code',value:'482',error:'Enter all 6 digits.'});add('disabled',{label:'6-digit code',value:'482913',disabled:true});}

if(kind==='slider')add('media',{variant:'media',label:'Seek prototype',min:0,max:120,value:32,format:v=>'0:'+String(v).padStart(2,'0')});
