const H=TurboUI;let active=new URLSearchParams(location.search).get('tab')||'Spends';if(!['Spends','Members','Analytics'].includes(active))active='Spends';
document.getElementById('statusbar').append(H.statusbar());
document.getElementById('nav').append(H.navigation({title:'Hub Details',left:{label:'Back to flow references',icon:'navigation-back',href:'../../flow-reference/index.html'},right:{label:'Help',icon:'help',onClick:()=>{}}}));

let savedLimits={};try{savedLimits=JSON.parse(sessionStorage.getItem('turbo-hub-spending-limits'))||{}}catch{}
const transactions=[['Amazon','04 Dec 2023, 10:00 PM',1595],['BESCOM','03 Dec 2023, 01:25 AM',710],['INOX Leisure Ltd','01 Dec 2023, 07:00 PM',350],['Swiggy','28 Nov 2023, 11:42 AM',1200],['Nykaa','27 Nov 2023, 01:45 PM',2400],['Amazon','25 Nov 2023, 07:00 PM',450],['Big Basket','22 Nov 2023, 10:00 PM',400],['Gupta Stores','22 Nov 2023, 10:00 PM',3200]];
const E=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls;if(text)e.textContent=text;return e};
function rows(items){const box=E('div','row-list');items.forEach(([name,detail,amount])=>box.append(H.row({name,detail,amount})));return box}
function section(title,content){const s=E('section','panel-section');s.append(E('h2','section-heading',title),content);return s}
function render(){document.getElementById('overview').replaceChildren(H.summary({variant:'centered',action:{label:'Hub options',icon:'more',onClick:()=>{}}}),H.limit({spent:active==='Members'?0:14500,limit:savedLimits.hub??100000,label:'Monthly Limit',variant:'circular'}));document.body.dataset.reference=active==='Members'?'members':active==='Analytics'?'analytics':'spends';const tabs=document.getElementById('tabs');tabs.replaceChildren(H.tabs({items:['Spends','Members','Analytics'],selected:active,onChange:value=>{active=value;render();document.querySelector('.phone-content').scrollTop=0;history.replaceState(null,'','?tab='+active)}}));const panel=document.getElementById('hub-panel');panel.setAttribute('aria-labelledby','hub-tab-'+['Spends','Members','Analytics'].indexOf(active));panel.replaceChildren();
if(active==='Spends'){const list=E('div','transaction-list');list.setAttribute('aria-label','Recent transactions');transactions.forEach(([name,detail,amount])=>list.append(H.row({name,detail,amount,variant:'compact'})));panel.append(list);const footer=E('div','full-action');footer.append(H.button({label:'Show all transactions',onClick:()=>{}}));panel.append(footer)}
if(active==='Members'){let invites=[];try{invites=JSON.parse(sessionStorage.getItem('turbo-hub-members'))||[]}catch{}const top=E('div','section-top');top.append(E('h2','section-heading',(2+invites.length)+' members'),H.button({label:'Add',icon:'caret-down',iconPosition:'end',size:'compact',quiet:true,href:'../add-member/index.html'}));const members=E('div','member-list');members.append(H.member({name:'Arun Sharma',role:'Manager',spent:0,limit:savedLimits.arun??45000,variant:'profile'}),H.member({name:'Kavya Sharma',role:'Manager',relation:'Wife',pending:true,variant:'profile'}));invites.forEach(member=>members.append(H.member({...member,variant:'profile'})));panel.append(top,members)}
if(active==='Analytics'){panel.append(H.chart({}));const spenders=E('div','spenders');[['Arun',20000],['Kavya',43000],['Neha',1200]].forEach(([name,value])=>{const s=E('div','spender');s.append(H.avatar({name}),E('span','',name),E('strong','','₹'+value.toLocaleString('en-IN')));spenders.append(s)});panel.append(section('Top spenders',spenders),section('Top categories',rows([['Essentials','10% of total spends',2320],['Shopping','35% of total spends',1350],['Bills & recharges','20% of total spends',710]])),section('Most used payment methods',rows([['HDFC Credit Card','XXXX 9132',10580],['ICICI Debit Card','XXXX 4281',4750],['UPI','Family Hub',2350]])))}
}render();
