/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_tesseractengine_free: (a: number, b: number) => void;
export const actionSchema: () => [number, number, number];
export const engineVersion: () => [number, number];
export const tesseractengine_applyAction: (a: number, b: any) => [number, number, number];
export const tesseractengine_applyBatch: (a: number, b: any) => [number, number, number];
export const tesseractengine_audioClockMs: (a: number) => [number, number];
export const tesseractengine_beginEditGroup: (a: number, b: number, c: number) => [number, number, number, number];
export const tesseractengine_cancelEditGroup: (a: number, b: number, c: number) => [number, number, number];
export const tesseractengine_commitEditGroup: (a: number, b: number, c: number) => [number, number, number];
export const tesseractengine_connectCanvas: (a: number, b: any) => any;
export const tesseractengine_create: (a: any) => any;
export const tesseractengine_dispose: (a: number) => void;
export const tesseractengine_document: (a: number) => [number, number, number];
export const tesseractengine_layerBounds: (a: number, b: number) => [number, number, number];
export const tesseractengine_loadResources: (a: number) => any;
export const tesseractengine_preloadAudio: (a: number) => void;
export const tesseractengine_pumpAudioScheduler: (a: number) => void;
export const tesseractengine_redo: (a: number) => [number, number, number];
export const tesseractengine_renderFrame: (a: number, b: number) => [number, number, number];
export const tesseractengine_setMuted: (a: number, b: number) => void;
export const tesseractengine_startPlayback: (a: number, b: number) => [number, number];
export const tesseractengine_stopPlayback: (a: number) => void;
export const tesseractengine_toBlob: (a: number) => [number, number, number];
export const tesseractengine_undo: (a: number) => [number, number, number];
export const version: () => [number, number];
export const wasm_bindgen__convert__closures_____invoke__hef4fac82b0e4ac33: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h86dbcf65592dd6c0: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h86dbcf65592dd6c0_5: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h921615c6b71e3686: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h27642f52cfd45577: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0607ec4f94b2e9fc: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h9edf9ca72c7be2b3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0607ec4f94b2e9fc_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h4c4c3de5e4ef96f2: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h8ae79ceefda28a64: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
