const H=TurboUI,params=new URLSearchParams(location.search),state=params.get('state')==='expired'?'expired':'declined';
const value=Number(params.get('amount')),amount=Number.isFinite(value)&&value>=1&&value<=1000000?value:2500;
const node=(tag,cls,text)=>{const n=document.createElement(tag);n.className=cls;if(text)n.textContent=text;return n};
document.getElementById('statusbar').append(H.statusbar());
document.getElementById('nav').append(H.navigation({title:'Payment request',left:{label:'Close request outcome',icon:'close',href:'../payment-review/index.html?amount='+amount}}));
document.getElementById('heading').append(H.pageHeader({heading:state==='expired'?'Approval request expired':'Approval request declined'}));
const content=document.getElementById('content'),art=node('div','request-outcome-icon');art.setAttribute('aria-hidden','true');art.innerHTML=TurboIcons.render(state==='expired'?'pending':'close',{size:48});
const result=node('section','request-outcome-copy');result.setAttribute('role','status');result.append(node('h2','','₹'+amount.toLocaleString('en-IN')+' at Nykaa'),node('p','',state==='expired'?'No approval was received before the request expired.':'Arun Sharma declined your payment request.'),node('p','','The payment was not completed.'));
content.append(art,result,H.button({label:'Back to payment review',href:'../payment-review/index.html?amount='+amount}));
window.addEventListener('DOMContentLoaded',()=>{document.querySelector('.preview-reference .preview-flow-navigation')?.remove();const nav=node('nav','preview-flow-navigation');nav.setAttribute('aria-label','Request outcome previews');for(const outcome of ['declined','expired']){const a=node('a','',outcome==='expired'?'Preview expired outcome':'Preview declined outcome');a.href='?state='+outcome+'&amount='+amount;nav.append(a);}const caption=node('p','','Proposed outcome · pending request shown as the Figma reference');document.querySelector('.preview-reference').append(caption,nav);});
