const H=TurboUI;let draft={location:'',radius:'500',permission:false};try{draft={...draft,...JSON.parse(TurboStoryContext.storage.getItem('turbo-hub-geofence'))}}catch{}
document.getElementById('statusbar').append(H.statusbar());document.getElementById('nav').append(H.navigation({title:'Pixel+ Tag setup',variant:'icons-only',left:{label:'Back to Card Keys',icon:'navigation-back',href:'../tag-added/index.html'}}));document.getElementById('heading').append(H.pageHeader({heading:'Configure a geofence',subtext:'Card Keys · Pixel+ Tag'}));
const form=document.createElement('form');form.className='geofence-form';form.noValidate=true;
const feedback=document.createElement('div');feedback.className='geofence-feedback';
const reset=()=>feedback.replaceChildren();
const place=H.field({id:'geofence-location',label:'Location or address',value:draft.location,placeholder:'Enter a place or address',onInput:value=>{draft.location=value;place.setError('');reset()}});
const radius=H.select({id:'geofence-radius',label:'Boundary radius',items:[['100','100 metres'],['250','250 metres'],['500','500 metres'],['1000','1 kilometre']],value:draft.radius,onChange:value=>{draft.radius=value;updateBoundary();reset()}});
const permission=H.check({id:'geofence-permission',label:'Allow location access for this tag',description:'Simulated permission for this prototype.',checked:draft.permission,onChange:value=>{draft.permission=value;permission.setError('');reset()}});
const boundary=document.createElement('div');boundary.className='geofence-boundary';boundary.setAttribute('role','img');const ring=document.createElement('span');ring.className='geofence-boundary-ring';const dot=document.createElement('span');dot.className='geofence-boundary-dot';ring.append(dot);const caption=document.createElement('p');boundary.append(ring,caption);
function updateBoundary(){caption.textContent=draft.radius+' m radius';boundary.setAttribute('aria-label','Illustrative boundary, '+draft.radius+' metre radius; no map coordinates');ring.style.width=({100:88,250:112,500:144,1000:176})[draft.radius]+'px';}updateBoundary();
form.append(place,radius,boundary,permission,H.button({label:'Save geofence',type:'submit'}),feedback);document.getElementById('content').append(form);
form.onsubmit=event=>{event.preventDefault();place.setError(draft.location.trim()?'':'Enter a location or address.');permission.setError(draft.permission?'':'Allow simulated location access to continue.');if(!draft.location.trim()){place.control.focus();return}if(!draft.permission){permission.control.focus();return}draft.location=draft.location.trim();TurboStoryContext.storage.setItem('turbo-hub-geofence',JSON.stringify(draft));feedback.replaceChildren(H.notice({message:'Geofence saved for Card Keys: '+draft.location+', '+draft.radius+' m radius',onDismiss:reset}));};
window.addEventListener('DOMContentLoaded',()=>document.querySelector('.preview-reference')?.append(Object.assign(document.createElement('p'),{textContent:'Proposed geofence editor · Delivery Details is the related form reference. Boundary is illustrative.'})));
