const chapters = [
 {role:'Manager',title:'Create a family Hub',intro:'The manager’s journey begins within PayZapp. They discover Turbo Hub, choose a family Hub, and connect an existing source account to create the shared space.',groups:[
  {title:'A familiar starting point',decision:'I placed Turbo Hub in Accounts & Cards, alongside the accounts users already manage. An introductory carousel explains shared spending and control before asking the manager to configure the Hub.',screens:[['Accounts & Cards','Turbo Hubs entry beneath linked cards.'],['Introduction','First carousel slide; remaining slides as a short sequence.']]},
  {title:'Purpose before setup',decision:'Hub types explain who the shared space is for. Naming the Hub and selecting a configured source account make its identity and funding clear; the created Hub then leads directly to inviting a member or adding a tag.',screens:[['Hub type','Family Hub selected.'],['Name & source','Hub name and existing credit/prepaid account.'],['Hub created','Success confirmation, Invite Member, and Add Pixel Tag.']]}
 ],refs:[['Discovery','VMJYp9g7DGyHWmhJZz1cQChc'],['Creation · right to left','irJNPUFcdMorYoJ08bUXa5fgmk']]},
 {role:'Manager',title:'Invite and manage members',intro:'With the Hub created, the manager adds family members and chooses their payment methods. The Hub dashboard becomes the place to check participation and understand spending.',groups:[
  {title:'Make access explicit',decision:'Payment methods describe what the member receives and any associated fee before the invitation is sent. In the Members view, pending invitations are stated on the member card so the manager can distinguish an invite from someone who has joined.',screens:[['Member details','Relationship, name, mobile, and optional nickname.'],['Payment methods','Physical Card, Digital Card, and UPI, with descriptions and fees.'],['Invitation status','Pending and joined members in the Members view.']]},
  {title:'From activity to oversight',decision:'Spends shows individual transactions, while Analytics highlights top spenders, categories, and payment methods. Monthly-limit summaries provide context for these amounts. The Hubs list separates spaces managed by the user from those managed by others; a proposed limit editor would complete the control flow.',screens:[['Spending','Merchant transactions and monthly spending.'],['Analytics','Top spenders, most-used cards, and categories.'],['Spending limit','Member/Hub, period, amount, and saved confirmation.','new'],['Other Hubs','Hubs list with Managed by Me / Managed by Others tabs.']]}
 ],refs:[['Invitation · right to left','keXcXE5lkhS5SPirkreik3BLM']],note:'The limit editor is suggested. The Hubs-list reference shows Managed by Me; Managed by Others is available as a tab.'},
 {role:'Member',title:'Join and set up payment access',intro:'The invitation brings the member into their side of the Hub. Their profile shows the available payment methods, monthly limit, and any setup still required.',groups:[
  {title:'Two entry paths, one destination',decision:'The source explores separate journeys for existing and new PayZapp users. The proposed entry screens make that distinction explicit: returning users proceed to the Hub, while new users first receive the account setup and introduction they need.',screens:[['Invitation','Inviter, Hub, and existing-account entry.','new'],['New-user entry','PayZapp entry and Turbo Hub introduction; new users only.','new']]},
  {title:'Show the next action in context',decision:'The delivery-details action sits beside the physical card marked Pending Action, while UPI is shown separately as active. A focused address form collects delivery information and returns to the profile with confirmation that the address was saved.',screens:[['Profile · pending action','Monthly limit, active UPI, and card delivery-details link.'],['Delivery details','Address, pincode, city/state, contact, and confirmation.'],['Address saved','Updated profile with the address-success message.']]}
 ],refs:[['Card setup','G4ExTT6ySA2J0WQb83q1BWijJ0w']],note:'Source onboarding labels are ambiguous; entry screens are proposed. Address submission is not proof of physical-card activation.'},
 {role:'Member + Manager',title:'Request, approve, and complete a payment',intro:'In this flow, Neha initiates a ₹2,500 payment at Nykaa using the family Hub. The transaction requires Arun’s authorization, connecting the member’s payment journey with the manager’s decision.',groups:[
  {title:'Member · Send the request',decision:'I retained PayZapp’s Scan & Pay pattern and kept the merchant, amount, and selected Hub account together during review. Once the request is sent, the pending state names the manager and shows an expiry countdown so the member knows who is responding and how long the request remains open.',screens:[['Scan QR','Nykaa merchant scanner.'],['Review payment','Nykaa, ₹2,500, family Hub account, and Swipe to Pay.'],['Request pending','Arun Sharma, ₹2,500, merchant, and expiry countdown.']]},
  {title:'Manager · Make an informed decision',decision:'The notification identifies the member, merchant, and amount before the manager opens the request. The detail screen repeats that context and offers Decline or Swipe to Authorize, followed by a distinct authorization confirmation.',screens:[['Notification','Neha, Nykaa, and ₹2,500 on the lock screen.'],['Review & authorize','Request details, Decline, and Swipe to Authorize.'],['Authorization confirmed','Manager’s request-authorized success state.']]},
  {title:'Member · Close the loop',decision:'Processing and the final receipt distinguish an authorized request from a completed payment. The receipt records the merchant, amount, and transaction details. Proposed declined and expired states would also give the member a clear outcome when authorization does not arrive.',screens:[['Processing','₹2,500 payment-processing state.'],['Payment receipt','Nykaa receipt, transaction details, and next actions.'],['Declined / expired','Two outcome variants with a clear next action.','new']]}
 ],refs:[['Scan','OOyc0Zq9BRNy8eRM7cFK8sNo23g'],['Review','pj5901B1DyQtj8DDjEgz0wXEaA'],['Pending','Z8wJc8fuEBUz3utfYZbLnu2Mls'],['Manager approval','Y16WMsQBYYXK4i16Uq3PzRaQUDs'],['Processing','8O2LAV3ua2Xc89uFVOUrY734oGA'],['Receipt','AEUUu7mF6h2FAlF8b5RqtQDDvA']],note:'The source does not establish the approval trigger. This sequence describes a payment requiring approval, not every payment.'},
 {role:'Manager · Optional',title:'Link a Pixel Tag',intro:'Beyond member payment methods, the manager can add a Pixel Tag to the Hub. This branch supports linking an existing tag or choosing between payment-only and tracking-capable options.',groups:[
  {title:'Explain the choice before linking',decision:'Images and descriptions distinguish Pixel Tag’s payment capability from Pixel+ Tag’s payment and tracking features. Existing owners can link their tag directly by scanning the QR code on its back.',screens:[['Link or buy','Existing-tag option and both tag types with images and capabilities.'],['Scan tag QR','Scanner with the instruction to scan the back of the tag.']]},
  {title:'Connect tracking to its setup',decision:'After linking, the Pixel+ Tag appears in the Hub with a geofence setup prompt attached to it. This keeps the unfinished action in context; the proposed configuration screens would carry that prompt through to a saved location boundary.',screens:[['Tag added','Card Keys tag with Configure Geofence / Setup Pixel+ Tag.'],['Geofence setup','Location, boundary/radius, permissions, and saved confirmation.','new']]}
 ],refs:[['Pixel Tag flow','L9fO641kjt3My4tVM92GN606kQ0']],note:'The source shows a geofence prompt; completed configuration is proposed.'}
];
const prototypes={'New-user entry':'invitation?audience=new','Geofence setup':'geofence-setup','Spending limit':'spending-limit','Declined / expired':'payment-unapproved?state=declined','Invitation':'invitation','Tag added':'tag-added','Scan tag QR':'tag-scanner','Link or buy':'pixel-tag','Accounts & Cards':'accounts-cards','Introduction':'onboarding','Scan QR':'scan-qr','Notification':'payment-notification','Other Hubs':'hubs','Hub type':'create-hub?step=type','Name & source':'create-hub?step=details','Hub created':'create-hub?step=created','Profile · pending action':'member-profile','Delivery details':'delivery-details','Address saved':'member-profile?saved=true','Request pending':'request-pending','Processing':'payment-processing','Payment receipt':'payment-receipt','Review & authorize':'payment-authorize','Authorization confirmed':'authorization-confirmed','Review payment':'payment-review','Member details':'add-member','Payment methods':'add-member?step=payments','Spending':'hub-dashboard?tab=Spends','Analytics':'hub-dashboard?tab=Analytics','Invitation status':'hub-dashboard?tab=Members'};
window.TurboFlowScreens=chapters.flatMap(chapter=>chapter.groups.flatMap(group=>group.screens)).filter(([name])=>prototypes[name]).map(([name])=>{const [route,query='']=prototypes[name].split('?');return {name,url:'../'+route+'/index.html'+(query?'?'+query:'')};});
