(function(){
const n=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!=null)e.textContent=text;return e};
const icon=(name,options={})=>{const e=n('span','th-icon');e.innerHTML=TurboIcons.render(name,{size:['navigation-back','more','help-fill'].includes(name)?24:20,...options});e.setAttribute('aria-hidden','true');return e};
const money=v=>'₹'+v.toLocaleString('en-IN');
const H=window.TurboUI={};
// Visual press feedback, also reusable by locked editorial playback. Never activates the control.
H.pressButton=button=>{
  if(!button||(!button.classList.contains('th-button')&&!button.classList.contains('th-avatar-edit'))||button.disabled||button.getAttribute('aria-disabled')==='true')return null;
  const win=button.ownerDocument.defaultView;
  if(win.matchMedia?.('(prefers-reduced-motion: reduce)').matches||!button.animate)return null;
  const style=win.getComputedStyle(button),scale=style.getPropertyValue('--button-press-scale').trim()||'.98';
  const duration=style.getPropertyValue('--button-press-duration').trim()||'120ms';
  const milliseconds=parseFloat(duration)*(duration.endsWith('ms')?1:1000);
  return button.animate([{scale:'1'},{scale,offset:.5},{scale:'1'}],{duration:milliseconds*2,easing:'ease-in-out'});
};
H.statusbar=({time='9:41',tone='chrome'}={})=>{const e=n('div','th-statusbar'+(tone==='light'?' th-statusbar--light':''));e.dataset.inspectorVariant=tone;e.setAttribute('aria-hidden','true');const signals=n('span','th-statusbar__signals');['signal','wifi','battery'].forEach(name=>{const glyph=icon(name);glyph.classList.add('th-statusbar__'+name);signals.append(glyph)});e.append(n('span','th-statusbar__time',time),signals);return e};
H.button=({label,icon:ico,quiet=false,iconOnly=false,disabled=false,onClick,href,type='button',size='default',iconPosition='start',variant='default',shape='default'})=>{const camera=variant==='camera';if(camera){iconOnly=true;quiet=false;size='default';}const b=n(href?'a':'button','th-button'+(quiet?' th-button--quiet':'')+(iconOnly?' th-button--icon':'')+(size==='compact'?' th-button--compact':''));if(camera){b.classList.add('th-button--camera');b.dataset.inspectorVariant='camera';}if(variant==='list'){b.classList.add('th-button--list');b.dataset.inspectorVariant='list';}if(variant==='danger'){b.classList.add('th-button--danger');b.dataset.inspectorVariant='danger';}if(variant==='glass'){b.classList.add('th-button--glass');b.dataset.inspectorVariant='glass';}if(variant==='warning'){b.classList.add('th-button--warning');b.dataset.inspectorVariant='warning';}if(variant==='inverse'){b.classList.add('th-button--inverse');b.dataset.inspectorVariant='inverse';}if(shape==='pill'){b.classList.add('th-button--pill');b.dataset.inspectorVariant=(variant==='default'?'':variant+'-')+'pill';}if(href)b.href=href;else{b.type=type;b.disabled=disabled;}if(iconOnly)b.setAttribute('aria-label',label);if(ico&&iconPosition!=='end')b.append(icon(ico,camera?{size:24,weight:'fill'}:{}));if(!iconOnly)b.append(document.createTextNode(label));if(ico&&iconPosition==='end'){b.append(icon(ico,camera?{size:24,weight:'fill'}:{}));b.dataset.inspectorVariant=size==='compact'?'compact-end':'trailing';}if(onClick)b.addEventListener('click',onClick);return b};
H.avatarEdit=({label='Edit Hub image',onClick,disabled=false}={})=>{const button=n('button','th-avatar-edit');button.type='button';button.disabled=disabled;button.setAttribute('aria-label',label);button.append(icon('edit'));if(onClick)button.addEventListener('click',onClick);return button;};
// App-owned identity artwork: replace the files in this one folder to update every avatar.
const avatarArtworkRoot=new URL('/app/assets/family-avatars/',document.currentScript.src);
H.avatarArtwork=Object.freeze({users:Object.freeze(Object.fromEntries(['arun','kavya','neha','rohan'].map(user=>[user,new URL(user+'.png',avatarArtworkRoot).href]))),home:new URL('family-home.png',avatarArtworkRoot).href});
const contextualAvatarSrc=(name,graphic)=>{const identity=name.trim().toLowerCase().replace(/\s+/g,' ');const user=identity.replace(/ sharma$/,'');if(Object.hasOwn(H.avatarArtwork.users,user))return H.avatarArtwork.users[user];return graphic&&(identity==='family'||/^the sharma(?:[’']?s)?$/.test(identity)||graphic==='hub')?H.avatarArtwork.home:null;};
H.avatar=({name='Family',large=false,graphic=false,size='default',src=null,editable=false,onEdit,editLabel='Edit Hub image',editDisabled=false,frame=false,badge=null})=>{if(badge==='success'){const wrapper=n('span','th-avatar th-avatar--badged');wrapper.dataset.inspectorVariant='badge-success';const mark=n('span','th-avatar__badge th-avatar__badge--success');mark.setAttribute('aria-hidden','true');mark.append(icon('success-heavy',{size:10}));wrapper.append(H.avatar({name,large,graphic,size,src,frame}),mark);return wrapper;}src=src||contextualAvatarSrc(name,graphic);if(editable){const wrapper=n('span','th-avatar th-avatar--editable');wrapper.dataset.inspectorVariant='editable';wrapper.append(H.avatar({name,large,graphic,size,src}),H.avatarEdit({label:editLabel,onClick:onEdit,disabled:editDisabled}));return wrapper;}const a=n('span','th-avatar'+(large?' th-avatar--large':'')+(size!=='default'?' th-avatar--'+size:''));if(frame)a.classList.add('th-avatar--framed');a.dataset.inspectorVariant=size!=='default'?size:large?'large':'initials';a.setAttribute('aria-hidden','true');const fallback=()=>{a.classList.remove('th-avatar--image');a.replaceChildren();if(graphic)a.append(icon(typeof graphic==='string'?graphic:size==='hub'?'hub':'family'));else a.textContent=name.trim().split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()};if(src){const image=n('img','th-avatar__image');image.alt='';image.decoding='async';image.addEventListener('error',fallback,{once:true});image.src=src;a.classList.add('th-avatar--image');a.append(image)}else fallback();return a};
H.badge=(text,{variant='default',icon:ico=null}={})=>{const badge=n('span','th-badge'+(variant!=='default'?' th-badge--'+variant:''));if(ico)badge.append(icon(ico,{size:12}));badge.append(document.createTextNode(text));badge.dataset.inspectorVariant=variant;return badge};
H.limit=({spent,limit,label='Monthly spending',variant='default',tone='surface',note='',action=null})=>{const circular=variant==='circular';const e=n('div','th-limit'+(circular?' th-limit--circular':'')+(variant==='member'?' th-limit--member':'')+(variant==='setup'?' th-limit--setup':'')+(tone==='glass'?' th-limit--glass':''));e.dataset.inspectorVariant=variant+(tone==='glass'?'-glass':'');if(variant==='setup'){const b=n(action?.href?'a':'button','th-limit th-limit--setup'+(tone==='glass'?' th-limit--glass':''));b.dataset.inspectorVariant=e.dataset.inspectorVariant;if(action?.href)b.href=action.href;else{b.type='button';if(action?.onClick)b.addEventListener('click',action.onClick);}b.append(icon(action?.icon||'plus'),n('span','th-limit__setup-label',action?.label||label));return b;}const head=n('div','th-limit__heading');const body=n('div');body.append(n('span','th-limit__label',label));const amount=n('span','th-limit__amount',money(spent));amount.append(n('small','',` / ${money(limit)}`));body.append(amount);const percent=limit>0?Math.min(100,Math.max(0,spent*100/limit)):0;const ratio=percent/100;const progress=n('div',circular?'th-limit__ring':'th-progress');progress.setAttribute('role','progressbar');progress.setAttribute('aria-label',label);progress.setAttribute('aria-valuemin','0');progress.setAttribute('aria-valuemax',String(Math.max(1,limit)));progress.setAttribute('aria-valuenow',String(Math.min(Math.max(0,spent),Math.max(1,limit))));progress.setAttribute('aria-valuetext',`${money(spent)} of ${money(limit)} · ${Math.round(percent)}% used`);if(variant==='member'){const fill=n('span');fill.style.width=percent+'%';progress.append(fill);const values=n('div','th-limit__values');for(const [value,caption] of [[spent,'Spent'],[limit,label]]){const column=n('div','th-limit__column');column.append(n('span','th-limit__value',money(value)),n('span','th-limit__caption',caption));values.append(column)}e.append(progress,values);return e}if(circular){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 45 45');svg.setAttribute('aria-hidden','true');svg.innerHTML=`<circle class="th-limit__ring-track" cx="22.5" cy="22.5" r="20"/><circle class="th-limit__ring-fill" cx="22.5" cy="22.5" r="20" stroke-opacity="${ratio>0?1:0}" pathLength="100" stroke-dasharray="${ratio*100} 100" transform="rotate(-90 22.5 22.5)"/>`;progress.append(svg);head.append(body,progress);e.append(head)}else{head.append(body,icon('analytics'));const fill=n('span');fill.style.width=ratio*100+'%';progress.append(fill);const foot=n('div','th-limit__foot');foot.append(n('span','',`${Math.round(percent)}% used`),n('span','',`${money(Math.max(0,limit-spent))} remaining`));e.append(head,progress,foot)}return e};
H.tabs=({items,selected,onChange,id='hub',tone='surface'})=>{const e=n('div','th-tabs'+(tone==='chrome'?' th-tabs--chrome':tone==='segmented'?' th-tabs--segmented':''));e.dataset.inspectorVariant=tone;e.setAttribute('role','tablist');e.setAttribute('aria-label','Hub sections');items.forEach((label,i)=>{const b=n('button','',label);b.type='button';b.id=id+'-tab-'+i;b.setAttribute('role','tab');b.setAttribute('aria-controls',id+'-panel');b.setAttribute('aria-selected',String(label===selected));b.tabIndex=label===selected?0:-1;b.onclick=()=>onChange(label);b.onkeydown=event=>{let j;if(event.key==='ArrowRight')j=(i+1)%items.length;if(event.key==='ArrowLeft')j=(i-1+items.length)%items.length;if(event.key==='Home')j=0;if(event.key==='End')j=items.length-1;if(j!=null){event.preventDefault();onChange(items[j]);document.getElementById(id+'-tab-'+j)?.focus()}};e.append(b)});return e};
H.row=({name,detail,amount,graphic='payment',variant='default',avatarSrc=null,by=''})=>{const compact=variant==='compact';const e=n('div','th-row'+(compact?' th-row--compact':''));e.dataset.inspectorVariant=variant;const a=H.avatar({name,size:compact?'merchant':'default',graphic,src:avatarSrc});const body=n('div','th-row__body');body.append(n('span','th-row__title',name));if(detail)body.append(n('span','th-row__detail',detail));const value=n('span','th-row__amount',typeof amount==='number'?money(amount):amount);if(by){const column=n('span','th-row__value');column.append(value,n('span','th-row__by',by));e.append(a,body,column)}else e.append(a,body,value);return e};
H.member=({name,role,relation,pending=false,spent=0,limit=45000,variant='default',statusText,chevron=false})=>{const profile=variant==='profile';const e=n('article','th-member'+(profile?' th-member--profile':''));e.dataset.inspectorVariant=profile?(pending?'profile-pending':'profile-joined'):(pending?'pending':'joined');e.setAttribute('aria-label',name);const identity=n('div','th-member__identity');const body=n('div','th-member__copy');body.append(n('div','th-member__name',name));const meta=n('div','th-member__meta');if(profile){if(relation)meta.append(H.badge(relation,{variant:'relationship'}));if(role)meta.append(H.badge(role,{variant:'role'}))}else{if(role)meta.append(H.badge(role));if(relation)meta.append(H.badge(relation))}if(meta.childElementCount)body.append(meta);identity.append(H.avatar({name,size:profile?'profile':'default'}),body);if(chevron){const go=icon('caret-right',{size:20});go.classList.add('th-member__chevron');identity.append(go);}e.append(identity);if(pending){const status=n('div','th-member__status');status.append(icon(profile?'warning-circle':'pending'),n('span','',statusText||(profile?name.split(' ')[0]+' is yet to join the hub':'Yet to join the Hub')));e.append(status)}else e.append(H.limit({spent,limit,label:profile?'Monthly Limit':'Monthly limit',variant:profile?'member':'default'}));return e};
H.chart=({values=[1800,2200,2100,3000,3400,4000,4975],total=4975})=>{const e=n('div','th-chart');e.append(n('div','th-chart__label','Spending trend'),n('div','th-chart__value',money(total)));const points=values.map((v,i)=>`${i*300/(values.length-1)},${130-v/6000*110}`).join(' ');const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 300 145');svg.setAttribute('role','img');svg.setAttribute('aria-label','Spending trend rises from '+money(values[0])+' to '+money(total));svg.innerHTML=`<path d="M0 135 H300 M0 85 H300 M0 35 H300" stroke="#e7edf6" fill="none"/><polygon points="0,145 ${points} 300,145" fill="#eaf2ff"/><polyline points="${points}" stroke="#1766dc" stroke-width="3" fill="none" stroke-linejoin="round"/>`;e.append(svg);const axis=n('div','th-chart__axis');axis.append(n('span','','Jan'),n('span','','Feb'),n('span','','Mar'),n('span','','Today'));e.append(axis);return e};
H.summary=({name='The Sharma’s',type='Family Hub',variant='default',tone='surface',action=null,person=null})=>{const centered=variant==='centered';const e=n('div','th-hub-summary'+(centered?' th-hub-summary--centered':'')+(tone==='chrome'?' th-hub-summary--chrome':''));e.dataset.inspectorVariant=(action?(centered?'centered-action':'default-action'):variant)+(tone==='chrome'?'-chrome':'');const body=n('div');body.append(n('h1','',name),n('p','',type));e.append(H.avatar({large:!centered,size:centered?'hub':'default',...(person?{name:person}:{graphic:true}),frame:tone==='chrome'}),body);if(action){const slot=n('div','th-hub-summary__action');slot.append(H.button({...action,quiet:true,iconOnly:true}));e.append(slot)}return e};
})();


TurboUI.navigation=({title='',variant='default',left=null,right=null}={})=>{const root=document.createElement("nav");root.className="th-navigation";root.setAttribute("aria-label",title+" navigation");root.dataset.inspectorVariant=variant==="icons-only"?(right?"icons-both":"icons-back"):left?(right?"both":"back"):"title";for(const [side,action] of [["left",left],["right",right]]){const slot=document.createElement("div");slot.className="th-navigation__slot th-navigation__slot--"+side;if(action)slot.append(TurboUI.button({...action,icon:["back","caret-left","arrow-left"].includes(action.icon)?"navigation-back":action.icon==="help"?"help-fill":action.icon,quiet:true,iconOnly:true}));root.append(slot)}const label=document.createElement("span");label.className="th-navigation__title";label.textContent=variant==="icons-only"?"":title;root.insertBefore(label,root.lastChild);return root};


TurboUI.pageHeader=({heading,subtext='',verified=false,icon=null,visual=null,action=null}={})=>{const root=document.createElement('section');root.className='th-page-header';const copy=document.createElement('div');copy.className='th-page-header__copy';const title=document.createElement('h1');title.className='th-page-header__title';title.append(document.createTextNode(heading));if(verified){const badge=document.createElement('span');badge.className='th-page-header__verified';badge.setAttribute('role','img');badge.setAttribute('aria-label','Verified merchant');badge.innerHTML=TurboIcons.render('success',{size:14});title.append(badge)}copy.append(title);if(subtext){const text=document.createElement('p');text.className='th-page-header__subtext';text.textContent=subtext;copy.append(text)}root.append(copy);if(icon||visual){const trailing=document.createElement('div');trailing.className='th-page-header__visual';trailing.setAttribute('aria-hidden','true');if(icon)trailing.innerHTML=TurboIcons.render(icon,{size:24});else trailing.append(visual);root.append(trailing)}if(action){root.classList.add('th-page-header--action');root.dataset.inspectorVariant='action';root.append(action)}return root};

TurboUI.actionFooter=({actions=[],content=[],label='Page actions'}={})=>{const root=document.createElement('footer');root.className='th-action-footer';root.setAttribute('aria-label',label);root.append(...content);for(const action of actions)root.append(TurboUI.button(action));return root;};
